site_name: Awesome Polars
site_description: A curated list of awesome Polars talks, tools, examples and articles.

docs_dir: ../

site_author: Dotta Damien
repo_name: ddotta/awesome-polars
repo_url: https://github.com/ddotta/awesome-polars

theme:
  name: 'material'
  palette:
    primary: 'purple'
    accent: 'deep purple'

extra_css:
  - 'css/extra.css'
extra_javascript:
  - js/extra.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ddotta

markdown_extensions:
  - admonition
  - codehilite:
      css_class: code
      use_pygments: false
      guess_lang: false
  - toc:
      permalink: true