site_name: Awesome Polars
site_description: A curated list of awesome Polars talks, tools, examples and articles.

docs_dir: ../docs/

theme:
  name: 'material'
  palette:
    primary: 'purple'
    accent: 'deep purple'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ddotta

markdown_extensions:
  - admonition
  - codehilite:
      css_class: code
      use_pygments: false
      guess_lang: false
  - toc:
      permalink: true